### ISSUE TITLE
installation via composer

### ISSUE THREAD

**Issue by melaxon** [elgentos/frontend2fa#3]
for some reason the composer will place this ext to both:
app/code/... and vendor/...
php bin/magento module:enable Elgentos_Frontend2FA will fail:

`php bin/magento module:enable Elgentos_Frontend2FA
Autoload error: Module 'Elgentos_Frontend2FA' from '/Users/yannislivasov/www/http/altcheckout/app/code/Elgentos/Frontend2FA' has been already defined in '/Users/yannislivasov/www/http/altcheckout/vendor/elgentos/frontend2fa'.`

The same your friend's module  juashyam/authenticator (or Neyamtux_Authenticator) does
The setup completed when I removed one copy from app/code

**Comment by peterjaap** [comment]
Remove it from app/code first.

**Comment by peterjaap** [comment]
Sorry, read too quick. Fixed in 0.1.4; https://github.com/elgentos/frontend2fa/releases/tag/0.1.4
